#!/bin/bash

HOST_INPUT="hostservers.txt"
DNS_INPUT="dnsservers.txt"
NUM_HOSTS=$(wc -l < "$HOST_INPUT")
NUM_DNS=$(wc -l < "$DNS_INPUT")
CSV="output.csv"; echo "" > "$CSV"

echo "hostname;rr;cdn" >> "$CSV"

I_HOSTS=0;

while read HOSTNAME
do 
	I_HOSTS=$((I_HOSTS+1));
	I_DNS=0;
	ARRAY=();
	ROUND_ROBIN_DETECTED=0;

	while read DNS_SERVER 
	do
		I_DNS=$((I_DNS+1));

		echo "host: ${I_HOSTS}/${NUM_HOSTS}   dns: ${I_DNS}/${NUM_DNS}"

		# Wszystkie adresy hostów zwracane przez kolejne DNSy są dodawane do tablicy
		HOST_ADDRESS=`dig +short +time=1 $HOSTNAME @$DNS_SERVER`

		if ! [[ $HOST_ADDRESS == *"connection timed out"* ]]; 
		then
		
			while read ADDRESS
			do
				ARRAY+=("$ADDRESS");
			done < <(echo "$HOST_ADDRESS")

			# Jeżeli DNS zwraca więcej niż jeden adres hosta, oznacza to rozkład ruchu pomiędzy hosty na poziomie serwera DNS
			HOST_ADDRESS_COUNT=`echo "$HOST_ADDRESS" | wc -l`
			if [ $HOST_ADDRESS_COUNT -gt 1 ]
			then
				ROUND_ROBIN_DETECTED=1;
			fi
		fi


	done <$DNS_INPUT

	# Raport końcowy - z tablicy wybierane są unikalne wpisy adresów IP hostów
	UNIQUES=($(for v in "${ARRAY[@]}"; do echo "$v";done| sort| uniq| xargs))

	if [ ${#UNIQUES[@]} -gt 1 ]
	then
		CDN_DETECTED=1;
	else
		CDN_DETECTED=0;
	fi

	echo "${HOSTNAME};${ROUND_ROBIN_DETECTED};${CDN_DETECTED}" >> "$CSV"

done <$HOST_INPUT




